module.exports = {
  presets: ['razzle/babel'],
  plugins: [
    'macros',
    '@loadable/babel-plugin',
    [
      'effector/babel-plugin',
      {
        factories: [
          "@withease/factories",
          '@/shared/pageRouting',
          '@/lib/createQuery',
          '@/lib/createFx',
          '@/shared/session',
          '@/shared/Seo',
          '@/shared/location',
          '@/shared/payments',
          '@/shared/recentlyUsed',
          '@/shared/createBreadcrumbs',
          '@/lib/createField',
          '@/lib/status',
          '@/lib/createMutation',
          '@/lib/services',
          '@/lib/remotePages',
          '@/features/catalog',
          '@/features/customer',
          '@/features/basket',
          '@/features/basket/cart',
          'src/features/basket/cart',
          'src/features/favorites/models/factory',
          '@/features/favorites',
          'src/pages/FavoriteList/models/factory',
          'src/pages/orders/model',
        ],
      },
    ],
    '@babel/plugin-proposal-numeric-separator',
  ].filter(Boolean),
};
